### ISSUE TITLE
Issues with Revive

### ISSUE THREAD

**Issue by CelticSpike** [fholger/openvr_fsr#111]
so this mod is awesome and I would really love it to work with Revive and it does work to an extent i.e. if I replace the openvr_api32/64 dlls with the one from this mod it technically works but for some reason the games are super dark and unplayable.

have tested with Lone Echo and Stormland and get the same issue. 

would be awesome if this worked as i could finally play these games without having to turn everything to LOW , and with the mod enabled I get playable FPS at higher settings. it's just too dark to enjoy them.

have tried fiddling with brightness settings in steamvr and using things like FPSVR but nothing works

**Comment by fholger** [comment]
Are you sure you are using the latest version of the mod? This used to be a bug in an earlier version, but it should be fixed and I did test Stormland; it was working fine for me.

**Comment by CelticSpike** [comment]
yep using v1.1 of the Mod . I can't figure it out. the mirrored display on my desktop looks correct but everything is really dark in the HMD, valve index btw. when I remove the mod its fine again in the HMD

**Comment by fholger** [comment]
The desktop mirror is never affected by the mod in any way, that's why it isn't showing any issues.

Please post the log file for Stormland.

**Comment by CelticSpike** [comment]
[openvr_mod.log](https://github.com/fholger/openvr_fsr/files/7383598/openvr_mod.log)

**Comment by CelticSpike** [comment]
so quick FYI. stripped everything out i.e. oculus, revive and steam VR and reinstalled from scratch and sadly the issue remains

**Comment by fholger** [comment]
Looks like a regression, unfortunately. RC1 works in the interim.

**Comment by CelticSpike** [comment]
RC1??

**Comment by fholger** [comment]
Yes, the older RC1 release: https://github.com/fholger/openvr_fsr/releases/tag/fsr_rc1

**Comment by CelticSpike** [comment]
Yep that release works for me .
Thank you so much for your work on this dude. 
I can "finally" play stormland without needing to turn all the settings down to "Butt Fucking ugly"

**Comment by fholger** [comment]
Should be fixed in v1.2.
